language: python
cache: pip

matrix:
  include:
    - env: TOXENV="py27-dj111-wt{112,113}"
      python: '2.7'
    - env: TOXENV="py34-dj111-wt{112,113}"
      python: '3.4'
    - env: TOXENV="py35-dj111-wt{112,113}"
      python: '3.5'
    - env: TOXENV="py36-dj111-wt{112,113}"
      python: '3.6'
    - env: TOXENV="flake8,isort"
      python: '3.6'

install:
  - pip install --upgrade pip wheel tox

script:
  - tox
